### ISSUE TITLE
Manual patched iso does not work in swiss

### ISSUE THREAD

**Issue by skx7** [DOL-Translations/puzzle-collection#10]
Tried to manually the latest version, showing some missing ycookie.szp and panepon.szp errors. The output iso does crash when booting on swiss. Would it already be possible to have a functioning partially patched iso if we exludes these parts from the compile.bat? Or we are still at an too early stage to play on real hardware? Thanks, looking forward to fully translated game by the way! Heavily appreciated!

> [INFO] Compiling patches - Please wait..
An error occurred: [Errno 2] No such file or directory: '../src/YCookie/fs/ycookie.szp'
Traceback (most recent call last):
  File "D:\DATA\TEMP\0_NGC\puzzle-collection-main\tools\decompress.py", line 75, in <module>
    main(args)
    ~~~~^^^^^^
  File "D:\DATA\TEMP\0_NGC\puzzle-collection-main\tools\decompress.py", line 61, in main
    with open(args.infile, "rb") as f:
         ~~~~^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../src/PuzzleLeague/fs/panepon.szp'
Traceback (most recent call last):
  File "D:\DATA\TEMP\0_NGC\puzzle-collection-main\tools\decompress.py", line 75, in <module>
    main(args)
    ~~~~^^^^^^
  File "D:\DATA\TEMP\0_NGC\puzzle-collection-main\tools\decompress.py", line 61, in main
    with open(args.infile, "rb") as f:
         ~~~~^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../src/YCookie/fs/ycookie.szp'
warning: source file not found: ..//src//PuzzleLeague//Graphics.asm
warning: unable to open target file: ..//src//PuzzleLeague///fs/panepon-eng.rel
error: file not found: ..//src//PuzzleLeague///fs/panepon.rel
..//src//PuzzleLeague//Main.asm:5:2: insert "/fs/panepon.rel"
bass: assembly failed
warning: unable to open target file: ..//src//YCookie///fs/ycookie-eng.rel
error: file not found: ..//src//YCookie///fs/ycookie.rel
..//src//YCookie//Main.asm:5:2: insert "/fs/ycookie.rel"
bass: assembly failed
IN=3361032 OUT=2548219
        1 file(s) moved.
IN=3531668 OUT=2581283
        1 file(s) moved.
FILE OPEN ERROR![../src/PuzzleLeague/fs/panepon-eng.rel]
The system cannot find the file specified.
The system cannot find the file specified.
FILE OPEN ERROR![../src/YCookie/fs/ycookie-eng.rel]
The system cannot find the file specified.
The system cannot find the file specified.
[INFO] Patches compiled
----------
Finished!
----------

**Comment by NewGBAXL** [comment]
The repo is a little wonky at the moment, you might have to manually extract the .szp files.
Download GCr from this link, and extract and **place ycookie.szp, panepon.szp**, and any other .szp files **in their respective folders** (`src/_/fs/`)
[https://www.romhacking.net/utilities/619/](https://www.romhacking.net/utilities/619/)

You will then have to to **run `compile.bat`**, then **extract the .iso in `/output/`** to folder, and **place the edited .szp files** (renamed to  their original names) **in the extracted iso folder**. Bit of a process but it's mainly because the .szp are too big to reimport without editing the filesystem table, which the repository does not currently do.

Nintendont is not supported at this time. It uses a specific patch for the JP ver. and is not applied correctly on US. 
Once the pull request has been accepted it should work on Nintendont.
[https://github.com/FIX94/Nintendont/pull/1237](https://github.com/FIX94/Nintendont/pull/1237)
Not sure if Swiss has a similar problem but it's likely.
Dolphin Emulator only for the time being. Will eventually fix these problems. Sorry for the inconvenience.

**Comment by skx7** [comment]
> The repo is a little wonky at the moment, you might have to manually extract the .szp files. Download GCr from this link, and extract and **place ycookie.szp, panepon.szp**, and any other .szp files **in their respective folders** (`src/_/fs/`) https://www.romhacking.net/utilities/619/

I now end up with only 1 remaining wanring as shown below. Any idea how to fix this one?

> [INFO] Compiling patches - Please wait..
warning: source file not found: ..//src//PuzzleLeague//Graphics.asm
IN=3361032 OUT=2548219
        1 file(s) moved.
IN=3531668 OUT=2581283
        1 file(s) moved.
IN=2670660 OUT=1111675
The system cannot find the file specified.
IN=1986136 OUT=480959
        1 file(s) moved.
[INFO] Patches compiled

> You will then have to to run compile.bat, then extract the .iso in /output/ to folder, and place the edited .szp files (renamed to their original names) in the extracted iso folder. Bit of a process but it's mainly because the .szp are too big to reimport without editing the filesystem table, which the repository does not currently do.


Can you clarify a bit more this part? So basically extracting all szip files from the output compile bat generated iso and keeping this files in the output folder to then re-compile.bat? You lost me here :)

**Comment by NewGBAXL** [comment]
to remove this last warning just create an empty file as /src/PuzzleLeague/Graphics.asm. Not needed to work, though.

with GCr, or Dolphin Emulator, extract the _modified_ .iso to a folder. It should look like this:
![image](https://github.com/user-attachments/assets/44093523-f833-41ac-95ee-810fe1d13b2b)
In the `files` folder you are going to move over the new files from the /src/_/fs/ folder
![image](https://github.com/user-attachments/assets/e8a07c60-34b8-47b4-9274-439709b5a82e)

after running `compile.bat` you should now have a few more .rel files in the same directories you put them in. Those were patched properly.
grab each _-eng.szp and rename to just _.rszp (i.e. move `dr_mario-eng`.szp to the extracted game folder, and then rename to `dr_mario.szp`, and overwrite the original)
![image](https://github.com/user-attachments/assets/6cbc5c6c-c47b-48bd-b963-959523bdd09e)

**Comment by NewGBAXL** [comment]
The repo has been fixed and now works with simply running compile.bat, no python needed.
